{ 
  "id":248841, 
  "Actors":[
    "Kerry Washington",
    "Columbus Short",
    "Guillermo Diaz",
    "Kate Burton",
    "Tony Goldwyn",
    "Jeff Perry",
    "Katie Lowes",
    "Darby Tanchfield",
    "Henry Ian Cusick",
    "Bellamy Young",
    "Joshua Malina"
  ],
  "Airs_DayOfWeek": "Thursday",
  "Airs_Time":"10 PM",
  "ContentRating":"TV-14",
  "FirstAired":"2012-04-05",
  "Genre":["Drama"],
  "IMDB_ID":"tt1837576",
  "Language":"en",
  "Network":"ABC",
  "Overview":"A former media relations consultant to the President, Olivia Pope (Kerry Washington) dedicates her life to protecting and defending the public images of our nation's elite. After leaving the White House, the power consultant opened her own firm, hoping to start a new chapter -- both professionally and personally -- but she can't seem to completely cut ties with her past. Slowly it becomes apparent that her staff, who specialize in fixing the lives of other people, can't quite fix the ones closest at hand -- their own.",
  "Rating":9.0,
  "RatingCount":6,
  "Runtime":60,
  "SeriesID":81035,
  "SeriesName":"Scandal (2012)",
  "Status":"Continuing",
  "added":"2011-05-18 01:13:02",
  "addedBy":189361,
  "banner":"graphical/248841-g2.jpg",
  "fanart":"fanart/original/248841-1.jpg",
  "lastupdated":1357723708,
  "poster":"posters/248841-2.jpg",
  "zap2it_id":"SH01419535"
}